### PR TITLE
Reduce multiple ajax calls when there are number of dep-dropdown

### PR DESCRIPTION
**Pull request by niceahsan**
## Issue:
When there are more than one interdependent dropdown so onchange it was sending n-1 ajax requests for every dropdown. 

## Solution:

You can simply avoid this problem by adding `dep-false` class in select of every interdependent dropdown.

### CODE REVIEW

**Comment by kartik-v** [comment]
Will need to understand this and why this is needed.

**Comment by niceahsan** [comment]
e.g we are using 4 Dep-dropdown. `d1, d2, d3` and` d4`. 

DropDown    Dependent on
`d1` ---->none
`d2`---->`d1`
`d3`---->`d1,d2`
`d4 `---->`d1,d2,d3`

When we select option of `d1`. Every dependent dropdown (`d2-d4`) load values itself according to `d1` value but if the value of `d1` is `empty` or `loadingText` so from `d2` to `d4`, every dropdown send ajax calls to get options. so why should we bear the cost of ajax calls if value of `d1` is not set.
In this case, if the value of the all dependent dropdown is not set so ajax call should not be send for that dropdown.

**Comment by kartik-v** [comment]
So to clarify, I presume this use case is only when you do not want ajax call triggered when value is empty or null.  

You want to control it via a CSS class `dep-false`, I feel in that case a new plugin property can be set for you to do this instead of adding a css class.

**Comment by niceahsan** [comment]
Ok I have added a property named `depFalse ` instead of class which will by default `false`.

**Pull request closed without merging**
